---
name: speedtest

services:
  speedtest:
    container_name: speedtest
    image: lscr.io/linuxserver/speedtest-tracker:latest
    network_mode: host
    restart: unless-stopped
    env_file:
      - config.env
      - config_secrets.env
    volumes:
      - volume_speedtest:/config

volumes:
  volume_speedtest:
    external: true
