---
name: speedtest

services:
  speedtest:
    container_name: speedtest
    image: lscr.io/linuxserver/speedtest-tracker:latest
    network_mode: host
    restart: unless-stopped
    environment:
      TZ:  "${DEVICE_TIMEZONE}"
      DISPLAY_TIMEZONE: "${DEVICE_TIMEZONE}"
      DATETIME_FORMAT: "j M Y, H:i"
      APP_KEY: "${APP_KEY}"
      APP_URL: "http://${ANSIBLE_IP}:80"
      PUID: ${ANSIBLE_UID}
      PGID: ${ANSIBLE_GID}
      SPEEDTEST_SCHEDULE: "0 4,12,20 * * *"
      DEFAULT_CHART_RANGE: month
      PUBLIC_DASHBOARD: true
      DB_CONNECTION: sqlite
    volumes:
      - volume_speedtest:/config

volumes:
  volume_speedtest:
    external: true
